resource_types:
  - name: blackduck
    type: docker-image
    source:
      repository: lgohr/blackduck-resource
      tag: latest

resources:
  - name: my-blackduck
    type: blackduck
    source:
      url: https://my.blackduck.server
      username: ((my-secret-username))
      password: ((my-secret-password))
      name: myProject
  - name: source-code
    type: git
    source:
      uri: https://github.com/concourse/git-resource.git
      branch: master

jobs:
  - name: scan
    plan:
      - get: source-code
        trigger: true
      - put: my-blackduck
        params: {directory: source-code}
